//! Entity data field and serializer IDs per client protocol, from
//! `data/entity_data.txt` (generated by `examples/entity_data.rs`).

use std::collections::HashMap;

const TABLE: &str = include_str!("../data/entity_data.txt");

/// Entity data tables of one client protocol.
#[derive(Debug, Default)]
pub(crate) struct Fields {
    /// Server serializer names by ID.
    pub(crate) serializer_names: Vec<String>,
    /// Client serializer ID by server serializer ID.
    pub(crate) serializers: Vec<Option<i32>>,
    /// Entity type name (no namespace) → client field index by server field index.
    pub(crate) fields: HashMap<String, Vec<Option<u8>>>,
}

impl Fields {
    pub(crate) fn load(protocol: i32) -> Option<Self> {
        let mut out = Fields::default();
        let mut inside = false;
        let mut found = false;
        for line in TABLE.lines() {
            let mut f = line.split(' ');
            match f.next() {
                Some("server") => out.serializer_names = f.map(String::from).collect(),
                Some("protocol") => {
                    inside = f.next().and_then(|p| p.parse::<i32>().ok()) == Some(protocol);
                    found |= inside;
                }
                Some("serializers") if inside => {
                    out.serializers = f.map(|v| v.parse().ok()).collect();
                }
                Some("entity") if inside => {
                    let Some(name) = f.next() else { continue };
                    let ids = f
                        .filter(|v| !v.is_empty())
                        .map(|v| v.parse().ok())
                        .collect();
                    out.fields.insert(name.to_string(), ids);
                }
                _ => {}
            }
        }
        found.then_some(out)
    }

    /// Server serializer ID of a name.
    #[cfg(test)]
    pub(crate) fn serializer(&self, name: &str) -> Option<i32> {
        self.serializer_names
            .iter()
            .position(|n| n == name)
            .and_then(|i| i32::try_from(i).ok())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_client_protocol_has_tables() {
        for p in 767..=776 {
            let f = Fields::load(p).unwrap();
            assert_eq!(f.serializers.len(), f.serializer_names.len(), "{p}");
            assert!(
                f.fields.contains_key("player") && f.fields.contains_key("item"),
                "{p}"
            );
        }
        assert!(Fields::load(777).is_none());
    }

    #[test]
    fn age_locked_is_dropped_before_26_1() {
        let f = Fields::load(774).unwrap();
        let cow = &f.fields["cow"];
        // 16 baby, 17 age locked (26.1+), 18 variant
        assert_eq!(cow[16], Some(16));
        assert_eq!(cow[17], None);
        assert_eq!(cow[18], Some(17));
        let arm = f.serializer("humanoid_arm").unwrap() as usize;
        assert_eq!(f.serializers[arm], Some(38));
        let dye = f.serializer("dye_color").unwrap() as usize;
        assert_eq!(f.serializers[dye], None);
    }
}
