//! Generates `data/via_mappings.txt`: the stand-ins of ViaVersion Mappings
//! (the diff files ViaBackwards' mappings are built from; free to copy and
//! use per its README) for every step from the server version down to the
//! oldest client.
//!
//! `cargo run -p pumbo-translate-mv --example via_mappings -- <Mappings> > data/via_mappings.txt`
//!
//! `<Mappings>`: a clone of https://github.com/ViaVersion/Mappings (the files
//! `mappings/diff/mapping-<newer>to<older>.json`).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use std::collections::BTreeMap;
use std::path::Path;
use std::process::Command;

/// Steps from the server version down, newest first: (diff, client protocol it ends in).
const STEPS: &[(&str, i32)] = &[
    ("26.3to26.2", 776),
    ("26.2to26.1", 775),
    ("26.1to1.21.11", 774),
    ("1.21.11to1.21.9", 773),
    ("1.21.9to1.21.7", 772),
    ("1.21.7to1.21.6", 771),
    ("1.21.6to1.21.5", 770),
    ("1.21.5to1.21.4", 769),
    ("1.21.4to1.21.2", 768),
    ("1.21.2to1.21", 767),
];

/// Diff sections the translator uses.
const SECTIONS: &[&str] = &[
    "blockstates",
    "items",
    "sounds",
    "particles",
    "entities",
    "attributes",
];

/// Our changes to the diffs: (step, section, from, to).
const OVERRIDES: &[(&str, &str, &str, &str)] = &[
    // ViaBackwards turns mannequins into players with a fake player list
    // entry; without that entry the client does not spawn them.
    ("1.21.9to1.21.7", "entities", "mannequin", "armor_stand"),
];

fn main() {
    let dir = Path::new(&std::env::args().nth(1).expect("path to the Mappings clone")).to_owned();
    let commit = Command::new("git")
        .arg("-C")
        .arg(&dir)
        .args(["rev-parse", "HEAD"])
        .output()
        .expect("git rev-parse");
    let commit = String::from_utf8(commit.stdout).unwrap();
    println!(
        "# Generated by examples/via_mappings.rs from ViaVersion Mappings {}; do not edit.",
        commit.trim()
    );
    println!(
        "# `step <client protocol> <diff>`, then `<section> <from> <to>`; `-` drops the entry,"
    );
    println!("# a trailing `[` keeps the state's properties.");
    for &(step, protocol) in STEPS {
        let path = dir.join(format!("mappings/diff/mapping-{step}.json"));
        let diff: BTreeMap<String, serde_json::Value> =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        println!("step {protocol} {step}");
        for &section in SECTIONS {
            let Some(entries) = diff.get(section).and_then(|v| v.as_object()) else {
                continue;
            };
            let mut entries: BTreeMap<&str, &str> = entries
                .iter()
                .map(|(from, to)| (from.as_str(), to.as_str().unwrap()))
                .collect();
            for &(s, sec, from, to) in OVERRIDES {
                if s == step && sec == section {
                    entries.insert(from, to);
                }
            }
            for (from, to) in entries {
                assert!(!from.contains(' ') && !to.contains(' ') && !to.starts_with("id:"));
                println!("{section} {from} {}", if to.is_empty() { "-" } else { to });
            }
        }
    }
}
